In [2]:
import mxnet
from mxnet import nd, gpu

https://mxnet.apache.org/api/python/docs/tutorials/getting-started/crash-course/6-use_gpus.html

In [3]:
x = nd.ones((3,4), ctx=gpu())

MXNetError: b'[17:32:56] /tmp/build/80754af9/libmxnet_1564766659613/work/src/imperative/imperative.cc:81: Operator _ones is not implemented for GPU.\nStack trace:\n  [bt] (0) /disk1/users/ekoerner/miniconda3/envs/argmining19-ssc/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x38e1c4) [0x7fe6e16921c4]\n  [bt] (1) /disk1/users/ekoerner/miniconda3/envs/argmining19-ssc/lib/python3.7/site-packages/mxnet/libmxnet.so(mxnet::Imperative::InvokeOp(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, mxnet::DispatchMode, mxnet::OpStatePtr)+0x914) [0x7fe6e1816684]\n  [bt] (2) /disk1/users/ekoerner/miniconda3/envs/argmining19-ssc/lib/python3.7/site-packages/mxnet/libmxnet.so(mxnet::Imperative::Invoke(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&)+0x383) [0x7fe6e1817243]\n  [bt] (3) /disk1/users/ekoerner/miniconda3/envs/argmining19-ssc/lib/python3.7/site-packages/mxnet/libmxnet.so(MXImperativeInvokeImpl(void*, int, void**, int*, void***, int, char const**, char const**)+0x9fd) [0x7fe6e16d62dd]\n  [bt] (4) /disk1/users/ekoerner/miniconda3/envs/argmining19-ssc/lib/python3.7/site-packages/mxnet/libmxnet.so(MXImperativeInvokeEx+0x533) [0x7fe6e16d7683]\n  [bt] (5) /disk1/users/ekoerner/miniconda3/envs/argmining19-ssc/lib/python3.7/site-packages/mxnet/_cy3/ndarray.cpython-37m-x86_64-linux-gnu.so(+0x11026) [0x7fe6d42fc026]\n  [bt] (6) /disk1/users/ekoerner/miniconda3/envs/argmining19-ssc/bin/python(_PyMethodDef_RawFastCallKeywords+0x264) [0x560627da3ab4]\n  [bt] (7) /disk1/users/ekoerner/miniconda3/envs/argmining19-ssc/bin/python(_PyCFunction_FastCallKeywords+0x21) [0x560627da3bd1]\n  [bt] (8) /disk1/users/ekoerner/miniconda3/envs/argmining19-ssc/bin/python(_PyEval_EvalFrameDefault+0x47a4) [0x560627e09e54]\n\n'

https://medium.com/@changrongko/nv-how-to-check-cuda-and-cudnn-version-e05aa21daf6c

https://beta.mxnet.io/install/index.html

https://beta.mxnet.io/install/validate-mxnet.html

In [1]:
import mxnet as mx
a = mx.nd.ones((2, 3), mx.gpu())
b = a * 2 + 1
b.asnumpy()

array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [2]:
a


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @gpu(0)>