In [1]:
import mxnet
from mxnet import nd, gpu

https://mxnet.apache.org/api/python/docs/tutorials/getting-started/crash-course/6-use_gpus.html

In [ ]:
x = nd.ones((3,4), ctx=gpu())

https://medium.com/@changrongko/nv-how-to-check-cuda-and-cudnn-version-e05aa21daf6c

https://beta.mxnet.io/install/index.html

https://beta.mxnet.io/install/validate-mxnet.html

In [1]:
import mxnet as mx
a = mx.nd.ones((2, 3), mx.gpu())
b = a * 2 + 1
b.asnumpy()

array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [2]:
a


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @gpu(0)>